/**
 * IBM watsonx Orchestrate — Embedded Agent Configuration
 *
 * This is the OFFICIAL embed method as generated by the IBM WxO portal
 * (Chat Settings → Embed Chat → Step 2 → Copy Snippet).
 *
 * The embed works by:
 *  1. Setting window.wxOConfiguration before any script runs
 *  2. Dynamically loading  ${hostURL}/webclient/wxoLoader.js
 *  3. Calling wxoLoader.init() on load
 *
 * wxoLoader.js reads from window.wxOConfiguration:
 *   • hostURL         (required)
 *   • orchestrationID (required)
 *   • rootElementID   (defaults to "WACCRoot" if omitted)
 *   • showLauncher    (true = floating button, false = render inline immediately)
 *   • clientVersion
 *   • token           (JWT for authenticated/secure embed)
 *
 * The loader then fetches:
 *   ${hostURL}/webclient/static/js/main.js   — full WxO webclient SPA
 *   ${hostURL}/webclient/static/css/main.css — WxO webclient styles
 *
 * agentId and agentEnvironmentId are passed as additional fields that the
 * loaded webclient SPA reads at runtime to target the specific agent and
 * deployment environment.
 */

const WATSONX_CONFIG = {
  // ── Required fields (read by wxoLoader.js) ────────────────────────────────
  hostURL:         'https://au-syd.watson-orchestrate.cloud.ibm.com',
  orchestrationID: 'b0c575c2b8e441e68b7b56f366cdc6d8_c8625ea1-09b5-421e-a74a-3a20c11817f4',
  clientVersion:   'latest',

  // ── Root element ──────────────────────────────────────────────────────────
  // The ID of the DOM element the WxO webclient will mount into.
  // wxoLoader.js creates this element automatically if it doesn't exist,
  // but we create it explicitly so we can control its position in the layout.
  rootElementID: 'wxo-root',

  // ── Launcher mode ─────────────────────────────────────────────────────────
  // true  → floating chat button in the corner (default portal behaviour)
  // false → renders the full chat window directly into rootElementID
  showLauncher: false,

  // ── Agent targeting (read by the webclient SPA at runtime) ────────────────
  agentId:            'f8514129-1eb7-461b-9a67-6afe0ee6a026',
  agentEnvironmentId: '41d415f2-7dcf-4f5f-b980-4191d11b4337',

  // ── Security / JWT (optional — leave empty for public/unauthenticated) ────
  // token: '',

  // ── CRN reference ─────────────────────────────────────────────────────────
  crn: 'crn:v1:bluemix:public:watsonx-orchestrate:au-syd:a/b0c575c2b8e441e68b7b56f366cdc6d8:c8625ea1-09b5-421e-a74a-3a20c11817f4::',

  // ── Loader URL (computed from hostURL + known path) ───────────────────────
  // Confirmed: GET https://au-syd.watson-orchestrate.cloud.ibm.com/webclient/wxoLoader.js
  // returns HTTP 200 with Content-Type: application/javascript — real JS, not HTML.
  get loaderURL() {
    return `${this.hostURL}/webclient/wxoLoader.js`
  },
}

export default WATSONX_CONFIG
