import { useEffect, useRef, useState } from 'react'
import CFG from '../config/watsonx.js'
import './WatsonxChat.css'

/**
 * WatsonxChat
 * ───────────
 * Integrates the IBM watsonx Orchestrate Embedded Agent using the OFFICIAL
 * embed method generated by the IBM WxO portal under:
 *   Chat Settings → Embed Chat → Step 2 → Copy Snippet
 *
 * The snippet IBM generates is:
 *
 *   <script>
 *     window.wxOConfiguration = {
 *       clientVersion: "latest",
 *       orchestrationID: "<ID>",
 *       hostURL: "https://<host>",
 *       rootElementID: "root",
 *       showLauncher: true,
 *       // token: "<CLIENT_JWT_GOES_HERE>",
 *       agentId: "<AGENT_ID>",
 *       agentEnvironmentId: "<ENV_ID>",
 *     };
 *     setTimeout(function () {
 *       const script = document.createElement('script');
 *       script.src = `${window.wxOConfiguration.hostURL}/webclient/wxoLoader.js`;
 *       script.addEventListener('load', function () { wxoLoader.init(); });
 *       document.head.appendChild(script);
 *     });
 *   </script>
 *
 * This component reproduces that exact sequence in React, with:
 *   • showLauncher: false  → renders the full chat inline (no floating button)
 *   • rootElementID: 'wxo-root' → a div we render inside our layout
 *   • Loading / error states while wxoLoader.js and main.js are fetching
 *
 * Confirmed facts (verified by live HTTP inspection):
 *   ✓  GET /webclient/wxoLoader.js → HTTP 200, application/javascript (real JS)
 *   ✓  GET /wxoLoader.js           → HTTP 200, text/html (the portal SPA — wrong path)
 *   ✓  wxoLoader.js requires: hostURL, orchestrationID
 *   ✓  wxoLoader.js then loads: /webclient/static/js/main.js (full WxO webclient SPA)
 *   ✓  The webclient SPA reads agentId + agentEnvironmentId from wxOConfiguration at runtime
 */

// Prevent double-injection under React 18 StrictMode double-invoke
let _loaderInjected = false

function WatsonxChat({ destinationName }) {
  const [phase, setPhase]     = useState('loading')  // loading | loaded | error
  const [errMsg, setErrMsg]   = useState('')
  const hasTimedOut            = useRef(false)

  useEffect(() => {
    let cancelled = false

    // ── 1. Set window.wxOConfiguration BEFORE loading the script ─────────────
    //    (wxoLoader.js reads this synchronously on execution — same pattern as
    //     the IBM portal's generated snippet)
    window.wxOConfiguration = {
      clientVersion:      CFG.clientVersion,
      orchestrationID:    CFG.orchestrationID,
      hostURL:            CFG.hostURL,
      rootElementID:      CFG.rootElementID,
      showLauncher:       CFG.showLauncher,     // false → render inline, no floating button
      agentId:            CFG.agentId,
      agentEnvironmentId: CFG.agentEnvironmentId,
    }

    // ── 2. Skip injection if the script is already in the DOM ─────────────────
    if (_loaderInjected || document.getElementById('wxo-loader-script')) {
      _loaderInjected = true
      // wxoLoader was already called; the webclient SPA may or may not have
      // finished mounting. Give it up to 10 s then assume success.
      const t = setTimeout(() => { if (!cancelled) setPhase('loaded') }, 2000)
      return () => { cancelled = true; clearTimeout(t) }
    }

    // ── 3. Dynamically load /webclient/wxoLoader.js ───────────────────────────
    //    Mirrors the setTimeout wrapper in the IBM-generated snippet.
    //    The setTimeout is intentional — gives the DOM a tick to settle before
    //    the loader appends its own CSS and JS.
    const inject = () => {
      const script   = document.createElement('script')
      script.id      = 'wxo-loader-script'
      script.src     = CFG.loaderURL   // hostURL + '/webclient/wxoLoader.js'
      script.async   = true

      script.addEventListener('load', () => {
        // ── 4. Call wxoLoader.init() exactly as the IBM snippet does ──────────
        if (typeof window.wxoLoader !== 'undefined' && typeof window.wxoLoader.init === 'function') {
          window.wxoLoader.init()
          // The loader now fetches /webclient/static/js/main.js asynchronously.
          // We can't hook into that directly, so we poll for the root element
          // being populated to know when the SPA has mounted.
          pollForMount(cancelled, setPhase)
        } else {
          if (!cancelled) {
            setErrMsg('wxoLoader.js loaded but window.wxoLoader.init is not defined.')
            setPhase('error')
          }
        }
      })

      script.addEventListener('error', () => {
        if (!cancelled) {
          setErrMsg(
            `Failed to load ${CFG.loaderURL}. ` +
            'Check your network connection. The IBM watsonx Orchestrate service must be reachable.'
          )
          setPhase('error')
        }
      })

      _loaderInjected = true
      document.head.appendChild(script)
    }

    // Wrap in setTimeout — mirrors the IBM-generated snippet exactly
    const injectTimer = setTimeout(inject, 0)

    // ── 5. Hard timeout ───────────────────────────────────────────────────────
    const timeout = setTimeout(() => {
      hasTimedOut.current = true
      if (!cancelled) {
        setErrMsg(
          'The IBM watsonx Orchestrate webclient took too long to load (30 s). ' +
          'Your IBM Cloud session may have expired. ' +
          'Log in at au-syd.watson-orchestrate.cloud.ibm.com and refresh.'
        )
        setPhase('error')
      }
    }, 30000)

    return () => {
      cancelled = true
      clearTimeout(injectTimer)
      clearTimeout(timeout)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <div className="wxo-chat-wrapper">

      {/* Loading overlay */}
      {phase === 'loading' && (
        <div className="wxo-loading">
          <div className="wxo-loading__anim">
            <div className="wxo-plane">✈️</div>
            <div className="wxo-loading__dots">
              <span /><span /><span />
            </div>
          </div>
          <h3 className="wxo-loading__title">Connecting to Travel Planner AI</h3>
          <p className="wxo-loading__sub">Loading IBM watsonx Orchestrate…</p>
          <div className="wxo-loading__bar">
            <div className="wxo-loading__bar-inner" />
          </div>
        </div>
      )}

      {/* Error state */}
      {phase === 'error' && (
        <div className="wxo-error">
          <div className="wxo-error__icon">⚠️</div>
          <h3 className="wxo-error__title">Connection Failed</h3>
          <p className="wxo-error__msg">{errMsg}</p>
          <div className="wxo-error__tips">
            <div className="wxo-error__tip">
              🔑 Log in at <strong>au-syd.watson-orchestrate.cloud.ibm.com</strong> first, then refresh
            </div>
            <div className="wxo-error__tip">📡 Check your internet connection</div>
            <div className="wxo-error__tip">🔍 Open browser console (F12) for IBM wxO error details</div>
          </div>
          <button className="wxo-error__retry" onClick={() => window.location.reload()}>
            🔄 Retry
          </button>
        </div>
      )}

      {/*
        Root element the WxO webclient SPA mounts into.
        wxoLoader.js reads rootElementID from window.wxOConfiguration and
        mounts the full chat UI here when showLauncher is false.

        Must always be in the DOM — wxoLoader.js looks it up by ID immediately
        after init() is called. Hidden while loading to prevent layout flash.
      */}
      <div
        id={CFG.rootElementID}
        className="wxo-chat-container"
        style={{
          visibility: phase === 'loaded' ? 'visible' : 'hidden',
          position:   phase === 'loaded' ? 'relative' : 'absolute',
          inset:      phase === 'loaded' ? 'auto' : 0,
          zIndex:     phase === 'loaded' ? 'auto' : -1,
        }}
      />

    </div>
  )
}

/**
 * Poll the root element until the WxO webclient SPA has injected content into it.
 * The SPA is loaded asynchronously by wxoLoader after init() — we can't hook
 * into its mount lifecycle directly, so we check for child nodes.
 */
function pollForMount(cancelled, setPhase) {
  const rootId  = window.wxOConfiguration?.rootElementID || 'wxo-root'
  const start   = Date.now()
  const MAX_MS  = 28000   // stay under the 30 s hard timeout

  const check = () => {
    if (cancelled) return
    const el = document.getElementById(rootId)
    if (el && el.childNodes.length > 0) {
      setPhase('loaded')
      return
    }
    if (Date.now() - start > MAX_MS) {
      // Timed out inside the poll — the hard timeout will handle the error state
      return
    }
    setTimeout(check, 400)
  }

  // Give the SPA's first render a head start before polling
  setTimeout(check, 800)
}

export default WatsonxChat
